# This is a GitHub Actions workflow configuration file

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

    
jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      #- name: Run ESLint
      #  run: npm run lint

      - name: Build Extension
        run: npm run build

      - name: Validate manifest.json
        run: |
          node -e "
          const fs = require('fs');
          const manifest = JSON.parse(fs.readFileSync('public/manifest.json', 'utf8'));
          if (!manifest.manifest_version || manifest.manifest_version !== 3) {
            throw new Error('Invalid or missing manifest_version');
          }
          if (!manifest.name || !manifest.version) {
            throw new Error('Manifest must include name and version');
          }
          "

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-build
          path: dist